# These are supported funding model platforms
github: [andeveldotcom]
custom: ["https://www.paypal.com/donate/?business=KCJQAJMG75HKU&no_recurring=0&item_name=By+making+a+small+donation%2C+you+can+support+the+development+of+the+free+software+published+on+www.andevel.com.&currency_code=EUR"]
