'------------------------------------------------------------------------------
' <auto-generated>
'     Tento kód byl generován nástrojem.
'     Verze modulu runtime:4.0.30319.42000
'
'     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
'     dojde-li k novému generování kódu.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    'pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    'Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    's parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    '''<summary>
    '''  Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("wapi_txt.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        '''  vyhledání prostředků pomocí třídy prostředků se silnými typy.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný &lt;!DOCTYPE Config
        '''[
        '''&lt;!ELEMENT Config (CredentialsFile?)&gt;
        '''&lt;!ELEMENT CredentialsFile (#PCDATA)&gt;
        ''']&gt;.
        '''</summary>
        Friend ReadOnly Property config_dtd() As String
            Get
                Return ResourceManager.GetString("config.dtd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný Copyright (c) 2023 Jan Angelovič
        '''http://www.andevel.com/WAPI-TXT/
        '''
        '''Permission is hereby granted, free of charge, to any person
        '''obtaining a copy of this software and associated documentation
        '''files (the &quot;Software&quot;), to deal in the Software without
        '''restriction, including without limitation the rights to use,
        '''copy, modify, merge, publish, distribute, sublicense, and/or sell
        '''copies of the Software, and to permit persons to whom the
        '''Software is furnished to do so, subject to the following
        '''conditions:
        '''        ''' [zbytek řetězce byl zkrácen];.
        '''</summary>
        Friend ReadOnly Property eula_txt() As String
            Get
                Return ResourceManager.GetString("eula.txt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný Description:
        '''This program create or delete TXT records in WEDOS DNS servers via WAPI. Usage:
        '''wapi-txt.exe [options] [&lt;command&gt; &lt;arg1&gt; &lt;arg2&gt; &lt;arg3&gt;]
        '''
        '''Options:
        '''--set wapi_credentials  Set access information for WAPI interface
        '''--config &lt;file&gt;         Path to config file
        '''--lets-secure           Program will works with txt related record only. 
        '''--no-check              Do not check command&apos;s arguments
        '''--version               Show version information
        '''--help                  Show help and usage informati [zbytek řetězce byl zkrácen];.
        '''</summary>
        Friend ReadOnly Property help_txt() As String
            Get
                Return ResourceManager.GetString("help.txt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný 0030
        '''0031
        '''0032
        '''0033
        '''0034
        '''0035
        '''0036
        '''0037
        '''0038
        '''0039
        '''0061
        '''0062
        '''0063
        '''0064
        '''0065
        '''0066
        '''0067
        '''0068
        '''0069
        '''006A
        '''006B
        '''006C
        '''006D
        '''006E
        '''006F
        '''0070
        '''0071
        '''0072
        '''0073
        '''0074
        '''0075
        '''0076
        '''0077
        '''0078
        '''0079
        '''007A
        '''00B7
        '''00E0
        '''00E1
        '''00E2
        '''00E3
        '''00E4
        '''00E5
        '''00E6
        '''00E7
        '''00E8
        '''00E9
        '''00EA
        '''00EB
        '''00EC
        '''00ED
        '''00EE
        '''00EF
        '''00F0
        '''00F1
        '''00F2
        '''00F3
        '''00F4
        '''00F5
        '''00F6
        '''00F8
        '''00F9
        '''00FA
        '''00FB
        '''00FC
        '''00FD
        '''00FE
        '''00FF
        '''0101
        '''0103
        '''0105
        '''0107
        '''0109
        '''010B
        '''010D
        '''010F
        '''0111
        '''0113
        '''0115
        '''0117
        '''0119
        '''011B
        '''011D
        '''011F
        '''0121
        '''01 [zbytek řetězce byl zkrácen];.
        '''</summary>
        Friend ReadOnly Property idna_chars_txt() As String
            Get
                Return ResourceManager.GetString("idna_chars.txt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        '''&lt;!--W3C Schema generated by XMLSpy v2023 rel. 2 (x64) (http://www.altova.com)--&gt;
        '''&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot;&gt;
        '''  &lt;xs:element name=&quot;arg&quot; type=&quot;xs:string&quot;/&gt;
        '''  &lt;xs:element name=&quot;option-set&quot;&gt;
        '''    &lt;xs:complexType&gt;
        '''      &lt;xs:sequence&gt;
        '''        &lt;xs:element ref=&quot;arg&quot;/&gt;
        '''      &lt;/xs:sequence&gt;
        '''      &lt;xs:attribute name=&quot;id&quot; type=&quot;xs:ID&quot;/&gt;
        '''    &lt;/xs:complexType&gt;
        '''  &lt;/xs:element&gt;
        '''  &lt;xs:element name=&quot;opt [zbytek řetězce byl zkrácen];.
        '''</summary>
        Friend ReadOnly Property parameters_xsd() As String
            Get
                Return ResourceManager.GetString("parameters.xsd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        '''
        '''  &lt;!-- Hlavní šablona pro kořenový element --&gt;
        '''  &lt;xsl:template match=&quot;/arguments&quot;&gt;
        '''    &lt;xsl:copy&gt;
        '''      &lt;xsl:choose&gt;
        '''        &lt;xsl:when test=&quot;.//command-create | .//command-delete&quot;&gt;
        '''          &lt;command-group&gt;
        '''            &lt;!-- Zde aplikujeme šablony pouze na přímé potomky --&gt;
        '''            &lt;xsl:apply-templates select=&quot;*&quot;/&gt;
        '''          &lt;/command-group&gt;
        '''        &lt;/xsl:when&gt;
        '''        &lt;xsl [zbytek řetězce byl zkrácen];.
        '''</summary>
        Friend ReadOnly Property parameters_xslt() As String
            Get
                Return ResourceManager.GetString("parameters.xslt", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
